# # Generic Maestro configuration
# # See https://maestro.mobile.dev/api-reference/configuration/workspace-configuration
# flows:
#   - "subFolder/*"
# includeTags:
#   - tagNameToInclude
# excludeTags:
#   - tagNameToExclude

# # Maestro Cloud only configuration
# baselineBranch: main
# # notifications:
# #   email:
# #     enabled: true
# #     recipients:
# #       - john@something.com
# # executionOrder:
# #     continueOnFailure: false # default is true
# #     flowsOrder:
# #         - flowA
# #         - flowB
# disableRetries: false
